// Code generated by MockGen. DO NOT EDIT.
// Source: categories_repository.go
//
// Generated by this command:
//
//	mockgen -source=categories_repository.go -destination=../mocks/categories_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/mytheresa/go-hiring-challenge/models"
	gomock "go.uber.org/mock/gomock"
)

// MockCategoriesStore is a mock of CategoriesStore interface.
type MockCategoriesStore struct {
	ctrl     *gomock.Controller
	recorder *MockCategoriesStoreMockRecorder
	isgomock struct{}
}

// MockCategoriesStoreMockRecorder is the mock recorder for MockCategoriesStore.
type MockCategoriesStoreMockRecorder struct {
	mock *MockCategoriesStore
}

// NewMockCategoriesStore creates a new mock instance.
func NewMockCategoriesStore(ctrl *gomock.Controller) *MockCategoriesStore {
	mock := &MockCategoriesStore{ctrl: ctrl}
	mock.recorder = &MockCategoriesStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCategoriesStore) EXPECT() *MockCategoriesStoreMockRecorder {
	return m.recorder
}

// CreateCategory mocks base method.
func (m *MockCategoriesStore) CreateCategory(category models.Category) (*models.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCategory", category)
	ret0, _ := ret[0].(*models.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCategory indicates an expected call of CreateCategory.
func (mr *MockCategoriesStoreMockRecorder) CreateCategory(category any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCategory", reflect.TypeOf((*MockCategoriesStore)(nil).CreateCategory), category)
}

// GetAllCategories mocks base method.
func (m *MockCategoriesStore) GetAllCategories() ([]models.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllCategories")
	ret0, _ := ret[0].([]models.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllCategories indicates an expected call of GetAllCategories.
func (mr *MockCategoriesStoreMockRecorder) GetAllCategories() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllCategories", reflect.TypeOf((*MockCategoriesStore)(nil).GetAllCategories))
}
