// Code generated by MockGen. DO NOT EDIT.
// Source: products_repository.go
//
// Generated by this command:
//
//	mockgen -source=products_repository.go -destination=../mocks/products_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	database "github.com/mytheresa/go-hiring-challenge/app/database"
	models "github.com/mytheresa/go-hiring-challenge/models"
	gomock "go.uber.org/mock/gomock"
)

// MockProductsStore is a mock of ProductsStore interface.
type MockProductsStore struct {
	ctrl     *gomock.Controller
	recorder *MockProductsStoreMockRecorder
	isgomock struct{}
}

// MockProductsStoreMockRecorder is the mock recorder for MockProductsStore.
type MockProductsStoreMockRecorder struct {
	mock *MockProductsStore
}

// NewMockProductsStore creates a new mock instance.
func NewMockProductsStore(ctrl *gomock.Controller) *MockProductsStore {
	mock := &MockProductsStore{ctrl: ctrl}
	mock.recorder = &MockProductsStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductsStore) EXPECT() *MockProductsStoreMockRecorder {
	return m.recorder
}

// GetAllProducts mocks base method.
func (m *MockProductsStore) GetAllProducts(filters database.ProductFilter) ([]models.Product, *int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllProducts", filters)
	ret0, _ := ret[0].([]models.Product)
	ret1, _ := ret[1].(*int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAllProducts indicates an expected call of GetAllProducts.
func (mr *MockProductsStoreMockRecorder) GetAllProducts(filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllProducts", reflect.TypeOf((*MockProductsStore)(nil).GetAllProducts), filters)
}

// GetProductByCode mocks base method.
func (m *MockProductsStore) GetProductByCode(code string) (*models.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductByCode", code)
	ret0, _ := ret[0].(*models.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductByCode indicates an expected call of GetProductByCode.
func (mr *MockProductsStoreMockRecorder) GetProductByCode(code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductByCode", reflect.TypeOf((*MockProductsStore)(nil).GetProductByCode), code)
}

// GetProductByID mocks base method.
func (m *MockProductsStore) GetProductByID(id uint) (*models.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductByID", id)
	ret0, _ := ret[0].(*models.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductByID indicates an expected call of GetProductByID.
func (mr *MockProductsStoreMockRecorder) GetProductByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductByID", reflect.TypeOf((*MockProductsStore)(nil).GetProductByID), id)
}
